(import (scheme base) (scheme file) (scheme read) (scheme vector) (scheme write))
(define addr-bit-size 64)
(define stack ())
(define heap (make-vector 16 ()))
(define stack-allocator (cons
	(lambda ()) (cons
	()
())))
(define open-0 (lambda (type parameter)
	(cond
		((equal? type "memory/stack") ((lambda ()
			)))
		((equal? type "memory/heap") ((lambda ()
			)))
		((equal? type "file") ((lambda ()
			)))
	)
))
(define close-0 (lambda (resource)

))
(define-library (builtins)
	(export
		(rename close-0 close)
		(rename lambda-0 lambda)
		(rename open-0 open)
		(rename read-0 read)
		(rename write-0 write)
	)
)
